<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>net.eiroca</groupId>
  <version>1.8.1</version>
  <packaging>jar</packaging>
  <artifactId>eJDBCDrivers</artifactId>
  <name>eJDBCDrivers</name>
  <organization>
    <name>net.eiroca</name>
    <url>www.eiroca.net</url>
  </organization>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <!-- JDBC Drivers -->
    <postgresql.version>42.7.7</postgresql.version>
    <sqlserver.version>13.2.0.jre8</sqlserver.version>
    <mysql.version>9.4.0</mysql.version>
    <ingres.version>12.0-4.4.4</ingres.version>
    <mongodb.version>5.5.1</mongodb.version>
    <db2.version>12.1.2.0</db2.version>
    <oracle.version>21.19.0.0</oracle.version>
    <derby.version>10.17.1.0</derby.version>
    <!-- maven -->
    <mvn-antrun-plugin.version>1.8</mvn-antrun-plugin.version>
    <mvn-assembly-plugin.version>3.2.0</mvn-assembly-plugin.version>
    <mvn-build-helper-plugin>3.0.0</mvn-build-helper-plugin>
    <mvn-checkstyle-plugin.version>3.1.2</mvn-checkstyle-plugin.version>
    <mvn-checksum-plugin.version>1.7</mvn-checksum-plugin.version>
    <mvn-clean-plugin.version>3.1.0</mvn-clean-plugin.version>
    <mvn-compiler-plugin.version>3.13.0</mvn-compiler-plugin.version>
    <mvn-dependecy-plugin.version>3.8.1</mvn-dependecy-plugin.version>
    <mvn-deploy-plugin.version>2.8.2</mvn-deploy-plugin.version>
    <mvn-gpg-plugin.version>1.6</mvn-gpg-plugin.version>
    <mvn-jar-plugin.version>3.4.2</mvn-jar-plugin.version>
    <mvn-javadoc-plugin.version>3.2.0</mvn-javadoc-plugin.version>
    <mvn-paranamer-plugin.version>2.8</mvn-paranamer-plugin.version>
    <mvn-pmd-plugin.version>3.15.0</mvn-pmd-plugin.version>
    <mvn-site-plugin.version>3.9.0</mvn-site-plugin.version>
    <mvn-spotbugs-plugin.version>4.2.0</mvn-spotbugs-plugin.version>
    <mvn-surefire-plugin.version>3.5.2</mvn-surefire-plugin.version>
    <!-- compile & test -->
    <jdk.version>1.8</jdk.version>
    <junit.version>4.13.2</junit.version>
    <servlet.version>3.1.0</servlet.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <build>
    <finalName>${project.name}-${project.version}</finalName>
    <plugins>
      <!-- Set a JDK compiler level -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${mvn-compiler-plugin.version}</version>
        <configuration>
          <source>${jdk.version}</source>
          <target>${jdk.version}</target>
        </configuration>
      </plugin>
      <!-- Make the jar -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>${mvn-jar-plugin.version}</version>
        <configuration>
          <!-- DO NOT include log4j.properties file in your Jar -->
          <excludes>
            <exclude>**/log4j.properties</exclude>
            <exclude>**/simplelogger.properties</exclude>
            <exclude>**/placeholder</exclude>
          </excludes>
          <archive>
            <addMavenDescriptor>false</addMavenDescriptor>
            <manifest>
              <addDefaultEntries>false</addDefaultEntries>
              <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              <addDefaultSpecificationEntries>false</addDefaultSpecificationEntries>
              <addBuildEnvironmentEntries>false</addBuildEnvironmentEntries>
              <addClasspath>true</addClasspath>
              <classpathPrefix>libs/</classpathPrefix>
            </manifest>
            <manifestEntries>
              <Build-Jdk>${jdk.version}</Build-Jdk>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
      <!-- Copy project dependency -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>${mvn-dependecy-plugin.version}</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <!-- exclude junit, we need runtime dependency only -->
              <includeScope>runtime</includeScope>
              <outputDirectory>${project.build.directory}/libs/</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <!-- Unit test surefire -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${mvn-surefire-plugin.version}</version>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>${postgresql.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc -->
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>${sqlserver.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <version>${mysql.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.ingres.jdbc/iijdbc -->
    <dependency>
      <groupId>com.ingres.jdbc</groupId>
      <artifactId>iijdbc</artifactId>
      <version>${ingres.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.mongodb/mongo-java-driver -->
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-sync</artifactId>
      <version>${mongodb.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.ibm.db2/jcc -->
    <dependency>
      <groupId>com.ibm.db2</groupId>
      <artifactId>jcc</artifactId>
      <version>${db2.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8 -->
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc8</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.ha/ons -->
    <dependency>
      <groupId>com.oracle.database.ha</groupId>
      <artifactId>ons</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.security/oraclepki -->
    <dependency>
      <groupId>com.oracle.database.security</groupId>
      <artifactId>oraclepki</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.nls/orai18n -->
    <dependency>
      <groupId>com.oracle.database.nls</groupId>
      <artifactId>orai18n</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.security/osdt_core -->
    <dependency>
      <groupId>com.oracle.database.security</groupId>
      <artifactId>osdt_core</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.security/osdt_cert -->
    <dependency>
      <groupId>com.oracle.database.security</groupId>
      <artifactId>osdt_cert</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.ha/simplefan -->
    <dependency>
      <groupId>com.oracle.database.ha</groupId>
      <artifactId>simplefan</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.jdbc/ucp -->
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ucp</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.oracle.database.xml/xdb -->
    <dependency>
      <groupId>com.oracle.database.xml</groupId>
      <artifactId>xdb</artifactId>
      <version>${oracle.version}</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/org.apache.derby/derbyclient -->
    <dependency>
      <groupId>org.apache.derby</groupId>
      <artifactId>derbyclient</artifactId>
      <version>${derby.version}</version>
    </dependency>
  </dependencies>
</project>